extesion property support
camunda/camunda-external-task-client-js pull request #264
Opened 2022-10-21 12:15 UTC by alainosorio

2022-10-24 09:25 UTC, yanavasileva commented
Hi @alainosorio,

Thank you for your contribution.
I created camunda/camunda-bpm-platform/issues/2854 to track the progress of this request.
I will send the ticket for a decision, please keep in mind that it could take a while to get back to you because of other team responsibilities. Thank you for your patience in advance. 
In case you would like to speed up the process you can already think about adding tests and documentation in the contribution.

Best regards,
Yana

2022-10-28 08:41 UTC, yanavasileva commented
@alainosorio 
To extend the documentation, please add the new property to bottom of client.subscribeTo table:
https://github.com/camunda/camunda-external-task-client-js/blob/master/docs/Client.md#clientsubscribetopic-options-handler
The existing test cases can be found here: https://github.com/camunda/camunda-external-task-client-js/blob/master/lib/Client.test.js#L209-L242

In case of any questions, please let us know.

2022-10-28 09:43 UTC, alainosorio commented
thanks @yanavasileva, will do and let you know

2022-11-01 07:09 UTC, yanavasileva reviewed
@alainosorio , you can add test data here:
https://github.com/camunda/camunda-external-task-client-js/blob/master/lib/__snapshots__/Client.test.js.snap#L25-L58

2022-11-01 07:09 UTC, yanavasileva commented on lib/Client.test.js
> +        extensionProperties: true,
Redundant comma:
```suggestion
        extensionProperties: true
```

2022-11-02 10:51 UTC, tasso94 requested changes
* The subscription option to fetch extension properties is called `includeExtensionProperties`.
* It is not possible to filter for extension properties – only no or all extension properties will be fetched.

2022-11-02 10:51 UTC, tasso94 commented on docs/Client.md
> +| extensionProperties | A value which allow to fetch extensionProperties     | boolean |          |                                                       |
```suggestion
| includeExtensionProperties | A value which allow to fetch `extensionProperties`     | boolean |          |                                                       |
```

2022-11-02 10:51 UTC, tasso94 commented on lib/Client.js
> +          extensionProperties
```suggestion
          includeExtensionProperties
```

2022-11-02 10:51 UTC, tasso94 commented on lib/Client.js
> +          topic.extensionProperties = extensionProperties;
```suggestion
        if (!isUndefinedOrNull(includeExtensionProperties)) {
          topic.includeExtensionProperties = includeExtensionProperties;
```

2022-11-02 10:51 UTC, tasso94 commented on lib/Client.test.js
> +        extensionProperties: ["property1", "property2"]
```suggestion        
        includeExtensionProperties: true
```

2022-11-02 10:51 UTC, tasso94 commented on lib/Client.test.js
> +    test("should subscribe to topic based on extensionProperties ", () => {
```suggestion
    test("should subscribe to topic with includeExtensionProperties = true", () => {
```

2022-11-02 10:51 UTC, tasso94 commented on lib/Client.test.js
> +        customConfig.extensionProperties
```suggestion
      expect(footopicSubscription.includeExtensionProperties).toBe(
        customConfig.includeExtensionProperties
```

2022-11-02 10:51 UTC, tasso94 commented on lib/__snapshots__/Client.test.js.snap
> +        ],
```suggestion
        "includeExtensionProperties": true,
```

2022-11-03 10:02 UTC, yanavasileva commented
@alainosorio  thank you for implementing the review hints. I will have a look and let you know once I merge the contribution as I believe we are on a good track with the PR already.

2022-11-03 10:03 UTC, alainosorio commented
> @alainosorio thank you for implementing the review hints. I will have a look and let you know once I merge the contribution as I believe we are on a good track with the PR already.

Thanks!

2022-11-04 08:43 UTC, yanavasileva approved these changes

2022-11-04 08:54 UTC, yanavasileva commented
Hi @alainosorio,

I adjusted the commit message according to our [CONTRIBUTING](https://github.com/camunda/camunda-bpm-platform/blob/master/CONTRIBUTING.md#commit-message-conventions) guidelines and merged the code with 170192f.
Thank you and I see you in your next contribution!

Best regards,
Yana

2022-11-04 08:54 UTC, closed without merging

2022-11-04 08:55 UTC, alainosorio commented
> Hi @alainosorio,
> 
> I adjusted the commit message according to our [CONTRIBUTING](https://github.com/camunda/camunda-bpm-platform/blob/master/CONTRIBUTING.md#commit-message-conventions) guidelines and merged the code with [170192f](https://github.com/camunda/camunda-external-task-client-js/commit/170192fd1b169229cc860e638b31f0216b3ba3a4). Thank you and I see you in your next contribution!
> 
> Best regards, Yana

Thanks!